### ISSUE TITLE
Font?

### ISSUE THREAD

**Issue by msit18** [msit18/msit18.github.io#13]
How do I make this my page's font? Or how do I change the font in general?

https://fonts.google.com/selection?category=Serif,Sans+Serif,Display,Monospace&sort=popularity&selection.family=Noticia+Text

**Comment by chonigbe** [comment]
https://github.com/msit18/msit18.github.io/blob/40189589ec222bcb85f30385591249ecfc882c41/css/header.css

You can add selectors on your css page as shown above,

and you have to import your selected fonts in the header/index.html document:
https://github.com/msit18/msit18.github.io/blob/c9c6965afe9e766c70155187030138d1ff014c3f/head/index.html

**Comment by chonigbe** [comment]
I chose play as a secondary font, but if you want it all to be the Noticia text, its easy to change back!

**Comment by msit18** [comment]
Thanks Bro! :D
